FROM mysql:8.0

# Variables de entorno para MySQL
ENV MYSQL_ROOT_PASSWORD=passwordRoot
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=java-user-deploy
ENV MYSQL_PASSWORD=java-user-deploy

# Exponer el puerto de MySQL
EXPOSE 3306